### ISSUE TITLE
IMPORTANT - Create new repo for NYTimes search

### ISSUE THREAD

**Issue by preraktrivedi** [bxr556/Flicks#2]
Please create a new repo for the 2nd assignment. Also, your readme needs to be updated as well.

**Comment by bxr556** [comment]
Hi Prerak,

I just created a new repo as per feedback. Here is the link.

https://github.com/bxr556/Assignment2.git

Please let me know if you have any questions.
Regards,
Jim

**Comment by preraktrivedi** [comment]
Thanks 👍

**Comment by bxr556** [comment]
Readme was updated by was in wrong folder ( in parent directory ). I moved it down to the right directory.

Thanks,
Jim

**Comment by bxr556** [comment]
Thanks. I fixed both as per your suggestion.

Please let me know if there is anything else.

Jim
